# This file is a template and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:jdk16

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key:
    files:
      - build.gradle
      - gradle.properties
  paths:
    - build
    - .gradle

assemble:
  stage: build
  script: ./gradlew assemble
  except:
    - develop
    - master
    - merge_requests
    - tags

check:
  stage: test
  script: ./gradlew check
  except:
    - develop
    - master
    - merge_requests
    - tags

build:
  stage: build
  script: ./gradlew build
  only:
    - develop
    - master
    - merge_requests
    - tags
  artifacts:
    paths:
      - build/libs/*.jar

release:
  before_script: []
  cache: []
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  only:
    - tags
  script:
    - "echo $CI_COMMIT_TAG: $CI_COMMIT_TITLE"
  variables:
    VERSION: "echo $CI_COMMIT_TAG | cut -c 2-"
  stage: deploy
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_MESSAGE"
    assets:
      links:
        - name: "fabric_switcheroo-$CI_COMMIT_TAG-dev.jar"
          url: "https://gitlab.com/NatoBoram/fabric-switcheroo/-/jobs/artifacts/$CI_COMMIT_TAG/raw/build/libs/fabric_switcheroo-$VERSION-dev.jar?job=build"
          link_type: "package"
        - name: "fabric_switcheroo-$CI_COMMIT_TAG-sources-dev.jar"
          url: "https://gitlab.com/NatoBoram/fabric-switcheroo/-/jobs/artifacts/$CI_COMMIT_TAG/raw/build/libs/fabric_switcheroo-$VERSION-sources-dev.jar?job=build"
          link_type: "package"
        - name: "fabric_switcheroo-$CI_COMMIT_TAG-sources.jar"
          url: "https://gitlab.com/NatoBoram/fabric-switcheroo/-/jobs/artifacts/$CI_COMMIT_TAG/raw/build/libs/fabric_switcheroo-$VERSION-sources.jar?job=build"
          link_type: "package"
        - name: "fabric_switcheroo-$CI_COMMIT_TAG.jar"
          url: "https://gitlab.com/NatoBoram/fabric-switcheroo/-/jobs/artifacts/$CI_COMMIT_TAG/raw/build/libs/fabric_switcheroo-$VERSION.jar?job=build"
          link_type: "package"
