
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
type = "mod"
name = "switcheroo"
description = "Switch your currently held item for an effective item when clicking on a block."
version = "1.0.11"
platform = "fabric"
license = "GPL-3.0-or-later"
source = "https://github.com/NatoBoram/switcheroo/"
homepage = "https://github.com/NatoBoram/switcheroo/"
author = "Nato Boram"

# These are global requirements
[requirements]
minecraft = ">=1.20"
fabricLoader = ">=0.14.21"

[dependencies]
cloth-config = ">=11.0.98+mpkg.1"
fabric = ">=0.83.0+1.20"
modmenu = ">=7.0.0+mpkg.1"

[dev]
buildCommand = "./gradlew build"
