
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
type = "mod"
name = "switcheroo"
description = "Switch your currently held item for an effective item when clicking on a block."
version = "1.0.13"
platform = "fabric"
license = "GPL-3.0-or-later"
source = "https://github.com/NatoBoram/switcheroo"
homepage = "https://github.com/NatoBoram/switcheroo"
author = "Nato Boram"

# These are global requirements
[requirements]
minecraft = ">=1.21"
fabricLoader = ">=0.15.11"

[dependencies]
cloth-config = ">=15.0.127+mpkg.1"
fabric = ">=0.92.0+1.21"
modmenu = ">=11.0.0-rc.4+mpkg.1"

[dev]
buildCommand = "./gradlew build"
