
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
type = "mod"
name = "switcheroo"
description = "Switch your currently held item for an effective item when clicking on a block."
version = "1.0.17"
platform = "fabric"
license = "GPL-3.0-or-later"
source = "https://github.com/NatoBoram/switcheroo"
homepage = "https://github.com/NatoBoram/switcheroo"
author = "Nato Boram"

# These are global requirements
[requirements]
minecraft = ">=1.21.5"
fabricLoader = ">=0.16.14"

[dependencies]
cloth-config = ">=18.0.145+mpkg.1"
fabric = ">=0.121.0+1.21.5"
modmenu = ">=14.0.0-rc.2+mpkg.1"

[dev]
buildCommand = "./gradlew build"
